### ISSUE TITLE
Hey Anna, Here is the situation I talked to you about

### ISSUE THREAD

**Issue by pulliam** [pulliam/spottygram#2]
@anna 
I assigned another issue to Phil as well, I hope someone will help me spot if and what I can be doing wrong.

https://github.com/pulliam/spottygram/blob/master/app.js
https://github.com/pulliam/spottygram/blob/master/views/login.ejs

``` javascript
var authenticate = function(username, password, callback) {
      db.collection('sessions').findOne({ username: username }, 
        function(err, data) { 
          if (err) { throw err; }
          console.log(data);
          bcrypt.compare( password, data.password_digest, function(isMatch) {
          console.log( 'password is ' + data.password_digest );
          if (isMatch) {
            callback(data);
            console.log('password match')
          } else {
            callback(false);
          }
        })
      });
    };
```

``` javascript
app.post('/login', function(req, res) {
      console.log('username: ' + req.body.username);
      console.log('password: ' + req.body.password);


      authenticate(req.body.username, req.body.password, 
        function(user){
          if (user) {
              req.session.username = user.username;
              req.session.userID = user._id;
              res.redirect('/');
          } else {
              res.redirect('/login');
          }
        });
    });
```

``` javascript
    app.post('/user', function(req, res){
      if (req.body.password.length > 7 && req.body.password === req.body.password_confirm) {
        var password = bcrypt.hashSync(req.body.password, 8);
        var username = req.body.username;
        db.collection('sessions').insert({username: username, password: password}, 
          function(err, result){
            console.log(result);
          });
        authenticate(req.body.username, req.body.password, function(user){
          if (user){
            req.session.username = user.username;
            req.session.userID = user._id;
            res.redirect('/all');
          } else {
            res.redirect('/');
          }
        });
      }
    });
```

This is what I have on sessions. It is "logging in" - A session is being stored in the cookies and I have access to the pages where I can only access logged in. What happens though is that if you try to log in with a non-existent user or use some wrong password, you will still log in successfully. I am guessing the problem is with the authentication and bcrypt perhaps. Or maybe with the database? It is storing in the database though when a new user is created. That's why I suspect it's some lack of knowledge on how to use sessions in my part, and maybe the bcrypt use. I tried a lot to figure out what could be going wrong, but Im not so familiar with sessions and all my trials to learn didn't work because everything seems to work fine and I get no errors. That's why Im not sure how to fix it.

**Comment by annarankin** [comment]
Hey Thais! One problem I noted with your `authenticate` method - the bcrypt `.compare` method's callback takes two parameters...

``` javascript
bcrypt.compare("bacon", hash, function(err, res) {
    // res == true
});
```

...whereas you're only passing it one:

``` javascript
          bcrypt.compare( password, data.password_digest, function(isMatch) {
          console.log( 'password is ' + data.password_digest );
          if (isMatch) {
            callback(data);
            console.log('password match')
          } else {
            callback(false);
          }
        })
```

That will certainly give you an unexpected result!

**Comment by pulliam** [comment]
@annarankin Thanks! Something is working now, but Im still having some problems. If I try to log in as someone that doesnt exist, it doesnt, but it also crash the app:  (Cannot read property 'password' of null)

```
/Users/thais/code/project_tbd/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'password' of null
    at /Users/thais/code/project_tbd/app.js:67:36
    at handleCallback (/Users/thais/code/project_tbd/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/thais/code/project_tbd/node_modules/mongodb/lib/collection.js:1335:5
    at handleCallback (/Users/thais/code/project_tbd/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/thais/code/project_tbd/node_modules/mongodb/lib/cursor.js:673:5
    at handleCallback (/Users/thais/code/project_tbd/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorNotified (/Users/thais/code/project_tbd/node_modules/mongodb-core/lib/cursor.js:563:3)
    at /Users/thais/code/project_tbd/node_modules/mongodb-core/lib/cursor.js:673:16
    at queryCallback (/Users/thais/code/project_tbd/node_modules/mongodb-core/lib/cursor.js:301:18)
    at Callbacks.emit (/Users/thais/code/project_tbd/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/Users/thais/code/project_tbd/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/Users/thais/code/project_tbd/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
```

``` javascript
//Sessions Authentication
var authenticate = function(name, password, callback) {
  db.collection('sessions').findOne({"username": name }, 
    function(err, data) { 
      if (err) {throw err;}
      bcrypt.compare(password, data.password, function(err, isMatch) {
      if (isMatch) {
        callback(data);
      } else {
        callback(false);
      }
    })
  });
};


app.post('/login', function(req, res) {
  console.log('username: ' + req.body.username);
  console.log('password: ' + req.body.password);

  authenticate(req.body.username, req.body.password, function(user){
      if (user) {
          req.session.username = user.username;
          req.session.userID = user._id;
          res.redirect('/');
      } else {
          res.redirect('/login');
      }
    });
});

app.post('/user', function(req, res){
  if (req.body.password === req.body.password_confirm) {

    var beforeencrypted = req.body.password;
    var password = bcrypt.hashSync(req.body.password, 8);
    var username = req.body.username;

    console.log('password is ' + beforeencrypted + 
      ' encrypted it is ' + password + ' and username is ' + username
      + ' req is ' + req + ' and res is ' + res + ' and password_confirm is ' +
      req.body.password_confirm);

    db.collection('sessions').insert({username: username, password: password}, 
      function(err, result){
        console.log('this was added in the database: \n' + result);
      }
    );

    authenticate(req.body.username, req.body.password, function(user){

      console.log('body.username: ' + req.body.username + '\nbody.password: ' +
       req.body.password)

      if (user){
        req.session.username = user.username;
        req.session.userID = user._id;
        res.redirect('/all');
      } else {
        res.redirect('/');
      }
    });
  }
});
```

**Comment by annarankin** [comment]
Yo! I'd check to see `if (!data) { callback(false) }` in your `authenticate` function.

**Comment by pulliam** [comment]
Thats works. It gives be back a console log "no data". How can I fix though? Would it be right to put a redirect inside that if? @annarankin

**Comment by pulliam** [comment]
Ok, that works! I will try to see how I can play with that and let you know If I need more help! Thanks Anna! 
PS: Can I start trying to deploy to heroku or is there something we haven't learned about it that could break the trial of doing so?
@annarankin 

``` javascript
var authenticate = function(name, password, callback) {
  db.collection('sessions').findOne({"username": name }, 
    function(err, data) { 
      if (err) { throw err; }
      if (!data) { 
        console.log('No Data');
        callback(false) 
      } else {
        bcrypt.compare(password, data.password, function(err, isMatch) {
          if (isMatch) {
            callback(data);
          } else {
            console.log('Didnt match database' + err);
            callback(false);
          }
        }
      }
  });
};
```

**Comment by annarankin** [comment]
Looking at your code, it looks like this will hit a redirect anyway -

``` javascript
app.post('/login', function(req, res) {
  console.log('username: ' + req.body.username);
  console.log('password: ' + req.body.password);

  authenticate(req.body.username, req.body.password, function(user){
// If you're passing false to the callback, user will be false and...
      if (user) {
          req.session.username = user.username;
          req.session.userID = user._id;
          res.redirect('/');
// You should hit this else and be redirected to the login
      } else {
          res.redirect('/login');
      }
    });
});
```
